### ISSUE TITLE
CallAPI Error with updatedPropertyDetails

### ISSUE THREAD

**Issue by WizardsEnterprise** [amassaro/Zillow.Services#1] opened 2018-06-22 21:00 UTC
When calling Client.GetUpdatedPropertyDetails("48749425") it returns an error stating that the xml response does not match up with the object that it's being deserialized into "There is an error in xml document (1, 1383)

**Comment by WizardsEnterprise** [comment] 2018-06-22 21:02
Inner Exception: Input String was not in a correct format

**Comment by WizardsEnterprise** [comment] 2018-06-22 21:18
The error is ocurring in CallAPI(), specifically during ser.Deserialize(new StringReader(xml)); where the class it's deserializing into is updatedPropertyDetails.

I've spent at least 10 hours trying to find and correct the issue but unfortunately I'm not fluent in deserializing xml or c# so I have not been able to locate the issue.

Please help.

**Comment by amassaro** [comment] 2018-06-22 21:35
Can you post a pastebin or the likes of the XML you are receiving and I can take a look?

**Comment by nbw71791** [comment] 2018-08-29 14:20
I am encountering the same issue. 
Line 106 of ZillowClient.cs is throwing the error. `return ser.Deserialize(new StringReader(xml));`

My output XML looks like below:

`"<?xml version=\"1.0\" encoding=\"utf-8\"?><UpdatedPropertyDetails:updatedPropertyDetails xmlns:UpdatedPropertyDetails=\"http://www.zillow.com/static/xsd/UpdatedPropertyDetails.xsd\" xsi:schemaLocation=\"http://www.zillow.com/static/xsd/UpdatedPropertyDetails.xsd https://www.zillowstatic.com/vstatic/b20c067/static/xsd/UpdatedPropertyDetails.xsd\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"><request><zpid>10604179</zpid></request><message><text>Request successfully processed</text><code>0</code></message><response><zpid>10604179</zpid><pageViewCount><currentMonth>1</currentMonth><total>1</total></pageViewCount><address><street>1601 Spring Garden St APT 412</street><zipcode>19130</zipcode><city>PHILADELPHIA</city><state>PA</state><latitude>39.9633</latitude><longitude>-75.165021</longitude></address><links><homeDetails>https://www.zillow.com/homedetails/1601-Spring-Garden-St-APT-412-Philadelphia-PA-19130/10604179_zpid/</homeDetails><photoGallery>https://www.zillow.com/homedetails/1601-Spring-Garden-St-APT-412-Philadelphia-PA-19130/10604179_zpid/#image=lightbox%3Dtrue</photoGallery><homeInfo>https://www.zillow.com/homedetails/1601-Spring-Garden-St-APT-412-Philadelphia-PA-19130/10604179_zpid/</homeInfo></links><editedFacts><useCode>Condominium</useCode><bedrooms>1</bedrooms><bathrooms>1.0</bathrooms><finishedSqFt>550</finishedSqFt><lotSizeSqFt>550</lotSizeSqFt><yearBuilt>1832</yearBuilt><numRooms>3</numRooms><heatingSources>Other</heatingSources><heatingSystem>Other</heatingSystem><coolingSystem>Central</coolingSystem><numUnits>1</numUnits></editedFacts><homeDescription>Secure doorman building in a fantastic location at a great price! Must see this lovely unit in the Colonnade! The building features security and a gym. The unit is a well proportioned 1 bedroom 1 bath with large living room, nice kitchen, large separate bedroom with closet, and laundry in unit. Steps to all that Center City has to offer and incredibly easy access to public transportation. Must see!</homeDescription><schoolDistrict>Philadelphia City</schoolDistrict></response></UpdatedPropertyDetails:updatedPropertyDetails><!-- H:042  T:106ms  S:817  R:Wed Aug 29 07:19:19 PDT 2018  B:5.0.55868-master.4045607~delivery_ready.3f5e1dc -->"`

**Comment by nbw71791** [comment] 2018-08-29 14:34
Looks like there is an issue with the XML schema.. Currently points to https://www.zillow.com/static/xsd/UpdatedPropertyDetails.xsd which is throwing an error.

**Comment by nbw71791** [comment] 2018-08-29 16:30
I reached out to Zillow support and received a pretty dismissive answer.

Is there any way to register and use a custom / local XSD file in the solution? I am not too familiar with XML either but the problem appears to be the fact that their XSD file for the UpdatedPropertyDetails.xsd is missing closing tags for 
`<xsd:element>
<xsd:sequence>
<xsd:complexType>`

in lines 4, 5, and 6.

**Comment by amassaro** [comment] 2018-08-29 16:52
I believe I fixed the XSD when I generated the c# code from it years back. There shouldn't be a need to embed the xsd. I will take a look at see what the issue might be.

**Comment by nbw71791** [comment] 2018-08-29 18:15
I have gotten it working with a few changes. Any insight into best practices would be great, this is my first experience with XML.

First, I replaced the XML line that was directing to the defunct UpdatedPropertyDetails.xsd hosted by Zillow to my own local version:

ZillowClient Line 105:

`if (t == typeof(updatedPropertyDetails))`
`                    {`
                       ` xml = xml.Replace(`
`                            "schemaLocation=\"http://www.zillow.com/static/xsd/UpdatedPropertyDetails.xsd https://www.zillowstatic.com/vstatic/b20c067/static/xsd/UpdatedPropertyDetails.xsd",
                            @"schemaLocation=""File:///PATH_TO_MY_CUSTOM_XSD File:///PATH_TO_MY_CUSTOM_XSD");`
`                    }`

Second, there was an issue with the returned XML where the bathroom value was being returned as a double. So I updated my custom UpdatedPropertyDetails.xsd so that the bathrooms field was a type double. 

Finally, I updated ZillowSchema.cs to reflect that change as well.

**Comment by amassaro** [comment] 2018-08-29 19:57
Definitely some good sleuthing here. I'll review the error tonight and search for a longer term solution. Or if you have something that works without having to load a local file and want to pull request it I'd be happy to take a look at that too. Also interesting on the bathroom find, I mean it makes sense but not sure why they'd not define it as such.

**Comment by amassaro** [comment] 2018-08-30 06:31
@nbw71791 I changed bathrooms type to float and it appears to have started working. I had some other pending code changes to the async api and another schema issue that I found a while ago that I push up with the last commit. Please confirm that the issue is resolved and I will close out the issue. Thanks.

**Comment by nbw71791** [comment] 2018-08-30 13:56
@amassaro, I just pulled down the changes and everything is working great. Consider it resolved.

**Comment by nbw71791** [comment] 2018-08-30 14:17
Also, thinking back on it. I imagine the bathroom field is a float because a home can have a "half bath".

**Comment by amassaro** [comment] 2018-08-30 15:38
@nbw71791 Yeah totally makes sense. Not sure why they have never updated the type OR fixed the XSD. I think originally I had created this library for use with another project back in 2007.

**Closed as completed by amassaro** 2018-08-30 15:38 UTC
